Sumin
SSUKYP/frontend pull request #18
Opened 2021-11-03 07:59 UTC by RaonPark

2021-11-03 11:50 UTC, vbalien requested changes

2021-11-03 11:50 UTC, vbalien commented on package.json
> +>>>>>>> 8bf17aa66a57c1e9fd42621d51d4db6aeb84f7b9
conflict marker 지워주세요...

2021-11-03 11:50 UTC, vbalien commented on webpack.config.ts
> +>>>>>>> 8bf17aa66a57c1e9fd42621d51d4db6aeb84f7b9
svg는 file-loader에서 처리하지 않게 해주시고 conflict marker 지워주세요.

2021-11-04 11:41 UTC, RaonPark commented
webpack 설정에서 svg 파일은 파일로더에 잡히지 않게 했고 package.json 파일에서 컨플릭트도 해결했습니다.

2021-11-04 13:17 UTC, vbalien approved these changes

2021-11-04 13:17 UTC, vbalien commented
squash merge 해주세요.

2021-11-05 04:53 UTC, merged